#!/bin/bash
#
#$ -P short ### queue
#$ -j y     ### have logoutput and erroroutput in the same file
#$ -o /dev/null
#$ -e /dev/null

LOGFILE=$2".out"

singularity exec /lfs/l1/legend/software/singularity/legendexp_legend-software_latest.sif bash -c "source /usr/local/bin/thisroot.sh && python main.py --config $1"
#cd gamma-fitter-BATv100 && make 
./gamma-fitter-BATv100/runGammaAnalysis  &> /lfs/l1/legend/users/bianca/gamma-analysis_TAUP/legend-gamma-lines-analysis/output/log/$LOGFILE